mqtt:
    host: xxxxxxxxxxxxx.home
    port: 8883 
    user: xxxxxxxx
    password: xxxxxxxxxxxxxxxxxxxx
    discovery: true #defaults to false, uncomment to enable home-assistant discovery
    discovery_prefix: homeassistant #change to match with setting of home-assistant
    ca_cert_path: "/path/to/rootCA.crt"
doors:
    -
      id: 'left'
      name: 'Left Garage Door'
      relay: 23
      state: 17
      state_topic: "home-assistant/cover/left"
      command_topic: "home-assistant/cover/left/set"
      invert_relay: true
    -
      id: 'right'
      name: 'Right Garage Door'
      relay: 24
      state: 27
      state_topic: "home-assistant/cover/right"
      command_topic: "home-assistant/cover/right/set"
      invert_relay: true
